title: Nicolás Budini
description: >-
  Physicist and university professor based in Argentina
theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Optional: Add your social links
github_username: nbudini
# twitter_username: yourusername

# Cayman theme specific
show_downloads: true
google_analytics: G-FBE9XX1P28
